{% set version = "2.7.0" %}

package:
  name: category_encoders
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/c/category_encoders/category_encoders-{{ version }}.tar.gz
    sha256: ee49c550fde511b222bac40c9c8740a7afdbe2431eaafd2aa43d4cec0bf92374
    folder: dist
  - url: https://github.com/scikit-learn-contrib/category_encoders/archive/{{ version }}.tar.gz
    sha256: 494cffe5d87c4dbce35ab97b8c93060e83acca3a38e91d9eb69da71d297925cd
    folder: src

build:
  noarch: python
  number: 0
  script:
    - cd dist
    - {{ PYTHON }} -m pip install -vvv . --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry-core
  run:
    - numpy >=1.14.0
    - pandas >=1.0.5
    - patsy >=0.5.1
    - python >={{ python_min }}
    - scikit-learn >=1.0.0,<1.6.0
    - scipy >=1.0.0
    - statsmodels >=0.9.0

test:
  source_files:
    - src/tests
  requires:
    - coverage
    - pip
    - python {{ python_min }}
    - pytest
    - pytest-subtests
  imports:
    - category_encoders
  commands:
    - pip check
    - coverage run --source=category_encoders --branch -m pytest src -vv --color=yes --tb=long -k "not (pandas_index or truncated_index)"
    - coverage report --show-missing --skip-covered --fail-under=89

about:
  home: https://github.com/scikit-learn-contrib/category_encoders
  license: BSD-3-Clause
  license_family: BSD
  license_file: dist/LICENSE.md
  summary: A collection of sklearn transformers to encode categorical variables as numeric
  doc_url: https://contrib.scikit-learn.org/category_encoders/
  description: |-
    A set of scikit-learn-style transformers for encoding categorical variables
    into numeric with different techniques. While ordinal, one-hot, and hashing
    encoders have similar equivalents in the existing scikit-learn version, the
    transformers in this library all share a few useful properties:

    - First-class support for pandas dataframes as an input (and optionally as
      output)

    - Can explicitly configure which columns in the data are encoded by name or
      index, or infer non-numeric columns regardless of input type

    - Can drop any columns with very low variance based on training set
      optionally

    - Portability: train a transformer on data, pickle it, reuse it later and
      get the same thing out.

    - Full compatibility with sklearn pipelines, input an array-like dataset
      like any other transformer

extra:
  recipe-maintainers:
    - bollwyvl
    - nirajd
    - wdm0006
